language: node_js
node_js:
  - node

script:
  - NODE_ENV=production yarn build
  - cp static/index.html    ./dist/
  - cp static/rtcstats.html ./dist/

deploy:
  skip_cleanup: true
  provider: pages
  local_dir: ./dist
  github_token: $GITHUB_TOKEN
  on:
    branch: master
